version: "3.9"

# define a template
x-croncertx:
  &default-croncertx
  build: .
  depends_on:
    - "auth-server"
    - "support-server"
    - "accounts-server"
  # restart: unless-stopped 
  # mount the nginx config for the back end
  # mount lets encrypt so certs doesn't get lost if the container stops
  volumes:
    - ./nginx:/etc/nginx/conf.d
    - ./certbot/certs:/etc/letsencrypt
    - ./certbot/logs:/var/log/letsencrypt
  env_file: .env
  ports:
    - 80:80
    - 443:443
  image: cycloss/croncertx:latest

services:
  # Use template
  croncertx-latest: *default-croncertx
  croncertx:
    <<: *default-croncertx
    image: cycloss/croncertx:$VERSION
